base_config:
  dataset:
    name: mackey_glass
    params:
      length: 10000
      train_ratio: 0.8
      seed: 42
  reservoir_bundle:
    topology:
      name: small_world
      params:
        n_nodes: 256
        k: 4
        beta: 0.2
        weight_scale: 1.0
    reservoir:
      spectral_radius: 0.9
      input_scale: 0.1
      random_seed: 0
  ridge_lam: 1.0e-2
  val_ratio: 0.2
  washout: 100

search_options:
  workers: 16
  target_mse: 0.01
  save_best: "configs/best_mackey_glass_config.npz"
  plot_best: true

param_grid:
  reservoir_bundle.topology.params.n_nodes: [50, 100, 256, 512]
  reservoir_bundle.topology.params.k: [2, 4, 8]
  reservoir_bundle.topology.params.beta: [0.1, 0.2, 0.5]
  reservoir_bundle.reservoir.input_scale: [0.01, 0.05, 0.1, 0.5, 1.0, 1.5]
  reservoir_bundle.reservoir.spectral_radius: [0.9, 0.95, 0.99, 1.0, 1.01, 1.05]
  reservoir_bundle.reservoir.random_seed: [0, 1, 2, 3]
  dataset.params.seed: [42, 1337]
  ridge_lam: [1.e-2, 1.e-3, 1.e-4, 1.e-5, 1.e-6]
